### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by julialongtin** [ga/Haskell#1]
I see no license on this work. I'd like to build on it, but...

**Comment by chrisjldoran** [comment]
Thanks, that's great. I hadn't got round to putting a license on it as it isn't finished! Are you fine if I use the most permissive one I can find?

**Comment by julialongtin** [comment]
Fine by me. My code is the most restrictive i can (AGPLv3+), so.. :)

**Comment by chrisjldoran** [comment]
If I was a proper coder like you I'd also take steps to protect my work!

**Comment by julialongtin** [comment]
Don't sell yourself short. PGA is really exciting! :)
